# Generated by Django 5.2.7 on 2025-10-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=50)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('insertion_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'crypto_prices',
                'unique_together': {('timestamp', 'symbol', 'market')},
            },
        ),
    ]
